services:

  app:
    labels:
      - traefik.enable=true
      - traefik.http.routers.language-learning.rule=Host(`www.easylingu.mertendieckmann.de`) || Host(`easylingu.mertendieckmann.de`)
      - traefik.http.routers.language-learning.entrypoints=websecure
      - traefik.http.routers.language-learning.tls=true
      - traefik.http.routers.language-learning.tls.certresolver=le-merten
      - traefik.docker.network=web
      - traefik.http.services.language-learning.loadbalancer.server.port=3000
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - web

networks:
  web:
    external: true