export enum ActivityType {
    LANGUAGE_STARTED = "LANGUAGE_STARTED",
    VOCABULARY_ADDED = "VOCABULARY_ADDED",
    VOCABULARY_MASTERED = "VOCABULARY_MASTERED",
    NEW_VOCABULARY_LEARNED = "NEW_VOCABULARY_LEARNED",
    PRACTICE_COMPLETED = "PRACTICE_COMPLETED",
    CHAT_INITIATED = "CHAT_INITIATED",
    SCENARIO_STARTED = "SCENARIO_STARTED",
    SCENARIO_COMPLETED = "SCENARIO_COMPLETED",
    GRAMMAR_ADDED = "GRAMMAR_ADDED",
    LEVEL_UP = "LEVEL_UP",
    WORD_CATEGORY_CREATED = "WORD_CATEGORY_CREATED",
    VOCABULARY_IMPORTED = "VOCABULARY_IMPORTED",
}